### ISSUE TITLE
status of extension

### ISSUE THREAD

**Issue by DanielRuf** [MichaelPerlbach/MM-Interactive#3]
@werkraum-admin @werkraum @MichaelPerlbach 

Hi there,

can you tell me what the current status of the extension is? So far it seems the extension is not completed and not usable?

Are there any alternative extensions which can be used or is this the only viable option for TYPO LTS 7?

**Comment by DanielRuf** [comment]
Bump.

**Comment by Shentao83** [comment]
Bump
